# Generated by Django 5.0.6 on 2024-12-31 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_testmodel_testbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testbook',
            options={'verbose_name': 'Test Booking', 'verbose_name_plural': 'Test Bookings'},
        ),
        migrations.AlterField(
            model_name='testbook',
            name='email',
            field=models.CharField(max_length=20, verbose_name='Customer Email'),
        ),
        migrations.AlterField(
            model_name='testbook',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='testbook',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Customer Phone'),
        ),
        migrations.AlterField(
            model_name='testbook',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.testmodel', verbose_name='Test'),
        ),
    ]
