# Generated by Django 5.0.6 on 2025-01-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_testbook_options_alter_testbook_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testbook',
            options={},
        ),
        migrations.AlterField(
            model_name='testbook',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Customer Email'),
        ),
        migrations.AlterField(
            model_name='testbook',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='testbook',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Customer Phone'),
        ),
    ]
