# Generated by Django 5.0.6 on 2025-01-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_testbook_options_alter_testbook_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbook',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
    ]
