# Generated by Django 5.0.6 on 2024-12-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
    ]
